### ISSUE TITLE
/getallwithrole fails on "Assistant GM"

### ISSUE THREAD

**Issue by blister** [RSC-NA/rsc#1]
Tested with a few other roles and they all seem fine. Assistant GM throws an error.

![image](https://github.com/RSC-NA/rsc/assets/124588/19a428b1-115b-4fa3-922f-a6da92b80c21)

**Comment by oddballmeasure** [comment]
Traceback:

```
1/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nickm/.local/share/Red-DiscordBot/data/rscbot2/cogs/CogManager/cogs/rsc/utils/utils.py", line 977, in _getallwithrole
    await interaction.response.send_message(embed=embed, ephemeral=True)
  File "/home/nickm/.virtualenvs/rscbot2/lib/python3.11/site-packages/discord/interactions.py", line 801, in send_message
    await adapter.create_interaction_response(
  File "/home/nickm/.virtualenvs/rscbot2/lib/python3.11/site-packages/discord/webhook/async_.py", line 221, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In data.embeds.0.fields.0.value: Must be 1024 or fewer in length.
[2024-04-05 10:49:32] [ERROR] red: Exception in command 'getallwithrole'
Traceback (most recent call last):
  File "/home/nickm/.virtualenvs/rscbot2/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nickm/.local/share/Red-DiscordBot/data/rscbot2/cogs/CogManager/cogs/rsc/utils/utils.py", line 977, in _getallwithrole
    await interaction.response.send_message(embed=embed, ephemeral=True)
  File "/home/nickm/.virtualenvs/rscbot2/lib/python3.11/site-packages/discord/interactions.py", line 801, in send_message
    await adapter.create_interaction_response(
  File "/home/nickm/.virtualenvs/rscbot2/lib/python3.11/site-packages/discord/webhook/async_.py", line 221, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In data.embeds.0.fields.0.value: Must be 1024 or fewer in length.
```

**Comment by xentrick** [comment]
This was fixed a long time ago
